#!/usr/bin/env ruby
require "rubygems"
require "bundler/setup"
require "mailman"

Mailman::Application.run do
  default do
    Ticket.create! name: message.subject, description: message.body.decoded
  end
end